/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class autopilot_vision_CubeDetectionJNI */

#ifndef _Included_autopilot_vision_CubeDetectionJNI
#define _Included_autopilot_vision_CubeDetectionJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     autopilot_vision_CubeDetectionJNI
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_autopilot_1vision_CubeDetectionJNI_setup
  (JNIEnv *, jclass);

/*
 * Class:     autopilot_vision_CubeDetectionJNI
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_autopilot_1vision_CubeDetectionJNI_cleanup
  (JNIEnv *, jclass);

/*
 * Class:     autopilot_vision_CubeDetectionJNI
 * Method:    locateUnitCubes
 * Signature: ([BIIZ)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_autopilot_1vision_CubeDetectionJNI_locateUnitCubes
  (JNIEnv *, jclass, jbyteArray, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
